{% set name = "ninja" %}
{% set version = "1.11.1" %}

package:
  name: {{ name }}-pkg
  version: {{ version }}

source:
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha256: 31747ae633213f1eda3842686f83c2aa1412e0f5691d1c14dbbcc67fe7400cea

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build_ninja.sh  # [unix]
    script: bld_ninja.bat  # [win]
    requirements:
      build:
        - {{ compiler("cxx") }}
        - python *

    test:
      commands:
        - ninja --version
{% if linux %}
  - name: python-{{ name }}
    script: build_python.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.7
        - setuptools
      run:
        - python >=3.7
        - {{ name }} =={{ version }}
    test:
      requires:
        - pip
      commands:
        - pip check
        - ${PYTHON} -m ninja --version
{% endif %}

about:
  home: https://ninja-build.org/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
    - xhochy
    - henryiii
  feedstock-name:
    - {{ name }}
