schema_version: 1

context:
  version: "1.13.0"

package:
  name: ninja
  version: ${{ version }}

source:
  url: https://github.com/ninja-build/ninja/archive/v${{ version }}.tar.gz
  sha256: f08641d00099a9e40d44ec0146f841c472ae58b7e6dd517bee3945cfd923cedf

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - make

tests:
  - package_contents:
      bin:
        - ninja
  - script:
      - ninja --version

about:
  license: Apache-2.0
  license_file: COPYING
  summary: A small build system with a focus on speed
  homepage: https://ninja-build.org/

extra:
  recipe-maintainers:
    - frol
    - xhochy
    - henryiii
    - baszalmstra
